"""The shared host-helper fixtures (test/helpers/cases.json), run against the
Python implementation.  They are generated by the Node reference
implementation, so a pass means both bindings agree."""

import json
import os
import posixpath
from datetime import datetime
from unittest import TestCase

import tree_sitter
import tree_sitter_okf
from tree_sitter_okf import okf

ROOT = os.path.join(os.path.dirname(__file__), "..", "..", "..")
CASES = os.path.join(ROOT, "test", "helpers", "cases.json")


def _source(case):
    if "source" in case:
        return case["source"].encode("utf-8")
    with open(os.path.join(ROOT, "test", "fixtures", "bundles", case["fixture"]), "rb") as f:
        return f.read()


def evaluate(case):
    parser = tree_sitter.Parser(tree_sitter.Language(tree_sitter_okf.language()))
    tree = parser.parse(_source(case))
    now = datetime.fromisoformat((case.get("now") or "2026-09-22T00:00:00Z").replace("Z", "+00:00"))
    cites = okf.citations(tree)
    return {
        "classify": okf.classify(case["path"], tree),
        "conceptId": okf.concept_id(posixpath.join("/bundle", case["path"]), "/bundle"),
        "frontmatter": okf.frontmatter(tree),
        "trustTier": okf.trust_tier(tree),
        "status": okf.status(tree),
        "isStale": okf.is_stale(tree, now),
        "generatedAt": okf.generated_at(tree),
        "duplicateKeys": okf.duplicate_keys(tree),
        "citations": {
            "references": [r["label"] for r in cites["references"]],
            "definitions": [d["label"] for d in cites["definitions"]],
            "unresolved": cites["unresolved"],
            "unused": cites["unused"],
        },
        "legacyCitations": okf.legacy_citations(tree),
        "conformance": [f["rule"] for f in okf.conformance(case["path"], tree, bool(case.get("bundleRoot")))],
    }


class TestHelpers(TestCase):
    def test_shared_cases(self):
        with open(CASES, encoding="utf-8") as f:
            cases = json.load(f)["cases"]
        for case in cases:
            with self.subTest(case["name"]):
                self.assertEqual(evaluate(case), case["expect"])
